apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25% 
  selector: 
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec: 
      containers:
      - name: product-service
        image: jjnovoap/product-service:latest
        imagePullPolicy: Always
        ports: 
          - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: DATABASE_URL
          - name: INVENTORY_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: INVENTORY_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe: 
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds:  10
          periodSeconds: 5