apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  INVENTORY_SERVICE_URL: http://inventory-service:8001
  DATABASE_URL: postgresql://admin:admin123@postgres:5432/ecommerce
  APP_ENV: "production"
  LOG_LEVEL: "info"